#ifndef WORD_TEMPLATES_DATA_H
#define WORD_TEMPLATES_DATA_H

#include <stdint.h>
#include <avr/pgmspace.h>

#include "goertzel.h"

#define WORD_COUNT           8
#define TEMPLATES_PER_WORD   2

#define STE_FEATURE_COUNT    31
#define ZCE_FEATURE_COUNT    31
#define GOERTZEL_FEATURE_COUNT_PER_BIN 31
#define TOTAL_GOERTZEL_FEATURE_COUNT   (GOERTZEL_NUM_BINS * GOERTZEL_FEATURE_COUNT_PER_BIN)

/* Layout: [STE×31 | ZCE×31 | G0×31 | G1×31 | G2×31 | G3×31] = 186 */
#define FEATURE_COUNT  (STE_FEATURE_COUNT + ZCE_FEATURE_COUNT + TOTAL_GOERTZEL_FEATURE_COUNT)

extern const char *const WORD_LABELS[WORD_COUNT];
extern const uint8_t WORD_TEMPLATES[WORD_COUNT][TEMPLATES_PER_WORD][FEATURE_COUNT] PROGMEM;

#endif
