#ifndef WORD_TEMPLATES_DATA_H
#define WORD_TEMPLATES_DATA_H

#include <stdint.h>
#include <avr/pgmspace.h>
#include "goertzel.h"

#define WORD_COUNT 8
#define TEMPLATES_PER_WORD 5
#define MAX_FEATURE_FRAMES 53
#define STE_FEATURE_COUNT MAX_FEATURE_FRAMES
#define ZCE_FEATURE_COUNT MAX_FEATURE_FRAMES
#define GOERTZEL_FEATURE_COUNT_PER_BIN MAX_FEATURE_FRAMES
#define TOTAL_GOERTZEL_FEATURE_COUNT (GOERTZEL_NUM_BINS * GOERTZEL_FEATURE_COUNT_PER_BIN)
#define TEMPLATE_CHANNEL_COUNT 7

extern const char *const WORD_LABELS[WORD_COUNT];
extern const uint8_t WORD_TEMPLATE_LENGTHS[WORD_COUNT][TEMPLATES_PER_WORD] PROGMEM;
extern const uint8_t WORD_TEMPLATES[WORD_COUNT][TEMPLATES_PER_WORD][TEMPLATE_CHANNEL_COUNT][MAX_FEATURE_FRAMES] PROGMEM;

#endif
