from __future__ import annotations

import argparse
import csv
from pathlib import Path

import numpy as np
from sklearn.cluster import KMeans

EXPECTED_SAMPLES_PER_WORD = 25
DEFAULT_TEMPLATES_PER_WORD = 5
RANDOM_STATE = 42


def load_features_csv(csv_path: Path) -> tuple[np.ndarray, np.ndarray, list[str]]:
    labels: list[str] = []
    rows: list[list[float]] = []

    with csv_path.open("r", encoding="utf-8", newline="") as csv_file:
        reader = csv.reader(csv_file)
        header = next(reader, None)
        if header is None:
            raise RuntimeError(f"CSV is empty: {csv_path}")
        if len(header) < 2:
            raise RuntimeError("CSV must contain label + feature columns")

        feature_headers = header[1:]

        for row in reader:
            labels.append(row[0])
            rows.append([float(value) for value in row[1:]])

    if not rows:
        raise RuntimeError(f"No samples found in CSV: {csv_path}")

    features = np.asarray(rows, dtype=np.float32)
    return features, np.asarray(labels), feature_headers


def extract_kmeans_templates(
    features: np.ndarray,
    labels: np.ndarray,
    templates_per_word: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    unique_labels = sorted(np.unique(labels))

    all_templates: list[np.ndarray] = []
    all_template_labels: list[str] = []
    all_template_ids: list[int] = []
    representative_indices: list[int] = []

    for label in unique_labels:
        label_indices = np.where(labels == label)[0]
        label_features = features[label_indices]

        if label_features.shape[0] != EXPECTED_SAMPLES_PER_WORD:
            raise RuntimeError(
                f"Expected {EXPECTED_SAMPLES_PER_WORD} samples for '{label}', found {label_features.shape[0]}"
            )
        if label_features.shape[0] < templates_per_word:
            raise RuntimeError(
                f"Cannot extract {templates_per_word} templates from {label_features.shape[0]} samples for '{label}'"
            )

        kmeans = KMeans(
            n_clusters=templates_per_word,
            random_state=RANDOM_STATE,
            n_init=10,
        )
        cluster_ids = kmeans.fit_predict(label_features)
        centroids = kmeans.cluster_centers_.astype(np.float32)

        for template_id, centroid in enumerate(centroids):
            cluster_member_local_indices = np.where(cluster_ids == template_id)[0]
            if cluster_member_local_indices.size == 0:
                raise RuntimeError(f"Empty cluster for '{label}' template {template_id}")

            cluster_members = label_features[cluster_member_local_indices]
            nearest_local_idx = int(
                cluster_member_local_indices[
                    np.argmin(np.linalg.norm(cluster_members - centroid, axis=1))
                ]
            )

            all_templates.append(centroid)
            all_template_labels.append(label)
            all_template_ids.append(template_id)
            representative_indices.append(int(label_indices[nearest_local_idx]))

    return (
        np.vstack(all_templates),
        np.asarray(all_template_labels),
        np.asarray(all_template_ids, dtype=np.int32),
        np.asarray(representative_indices, dtype=np.int32),
    )


def save_templates_csv(
    output_csv: Path,
    templates: np.ndarray,
    template_labels: np.ndarray,
    template_ids: np.ndarray,
    representative_indices: np.ndarray,
    feature_headers: list[str],
) -> None:
    output_csv.parent.mkdir(parents=True, exist_ok=True)

    with output_csv.open("w", encoding="utf-8", newline="") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(
            ["label", "template_id", "representative_sample_index", *feature_headers]
        )

        for label, template_id, sample_idx, template in zip(
            template_labels, template_ids, representative_indices, templates
        ):
            writer.writerow([label, int(template_id), int(sample_idx), *template.tolist()])


def main() -> None:
    output_dir = Path(__file__).resolve().parent / "output"

    parser = argparse.ArgumentParser(
        description="Extract 5 K-Means centroid templates from each word's 25 samples."
    )
    parser.add_argument(
        "--input-csv",
        type=Path,
        default=output_dir / "word_features.csv",
        help="Input features CSV generated by build_templates.py",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=output_dir / "word_templates.csv",
        help="Output templates CSV",
    )
    parser.add_argument(
        "--output-npz",
        type=Path,
        default=output_dir / "word_templates.npz",
        help="Output templates NPZ",
    )
    parser.add_argument(
        "--templates-per-word",
        type=int,
        default=DEFAULT_TEMPLATES_PER_WORD,
        help="How many templates to extract per word label",
    )

    args = parser.parse_args()

    features, labels, feature_headers = load_features_csv(args.input_csv)
    templates, template_labels, template_ids, representative_indices = extract_kmeans_templates(
        features=features,
        labels=labels,
        templates_per_word=args.templates_per_word,
    )

    save_templates_csv(
        output_csv=args.output_csv,
        templates=templates,
        template_labels=template_labels,
        template_ids=template_ids,
        representative_indices=representative_indices,
        feature_headers=feature_headers,
    )

    args.output_npz.parent.mkdir(parents=True, exist_ok=True)
    np.savez(
        args.output_npz,
        templates=templates,
        labels=template_labels,
        template_ids=template_ids,
        representative_sample_indices=representative_indices,
        feature_names=np.asarray(feature_headers),
    )

    print(f"Input samples: {len(labels)}")
    print(f"Templates extracted: {len(template_labels)}")
    print(f"Templates per word: {args.templates_per_word}")
    print(f"Saved: {args.output_csv}")
    print(f"Saved: {args.output_npz}")


if __name__ == "__main__":
    main()
